name: Demonstrate Bug

on:
  workflow_dispatch:

jobs:
  do_linux:
    name: Linux $GITHUB_PATH works between steps
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -p ~/.local/bin
        echo "~/.local/bin" >> $GITHUB_PATH
        echo "echo 'I am working.'" >> ~/.local/bin/works.sh
        chmod +x ~/.local/bin/works.sh

        ./works.sh
        works.sh

    - run: works.sh

  do_mac:
    name: macOS $GITHUB_PATH doesn't work between steps
    runs-on: macos-latest
    steps:
    - run: |
        mkdir -p ~/.local/bin
        echo "~/.local/bin" >> $GITHUB_PATH
        echo "echo 'I am working.'" >> ~/.local/bin/works.sh
        chmod +x ~/.local/bin/works.sh

        ./works.sh
        works.sh

    - run: works.sh
