name: Demonstrate Bug

on:
  workflow_dispatch:
  push:

jobs:
  test_github_path:
    strategy:
      matrix:
        os: [ ubuntu, macos, windows ]

    name: Test $GITHUB_PATH modifies $PATH on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
    - shell: bash
      run: |
        echo "PATH BEFORE: ${PATH}"
        mkdir -p ~/.local/bin
        echo "~/.local/bin" >> $GITHUB_PATH
        echo "echo 'I am working.'" >> ~/.local/bin/works.sh
        chmod +x ~/.local/bin/works.sh
        echo "PATH AFTER: ${PATH}"

        ~/.local/bin/works.sh
        works.sh

    - shell: bash
      run: works.sh
