name: Demonstrate Bug

on:
  workflow_dispatch:
  push:

jobs:
  test_github_path:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos, windows ]

    name: "${{ matrix.os }}: try $GITHUB_PATH"
    runs-on: ${{ matrix.os }}-latest
    steps:
    - shell: bash
      run: |
        # create a new bin path
        mkdir -p $HOME/.local/bin
        # make an script that prints "I am working." when it works
        echo "echo 'I am working.'" >> $HOME/.local/bin/works.sh
        # make the script executable
        chmod +x $HOME/.local/bin/works.sh

        # examine the path before
        echo "PATH BEFORE:"
        echo ${PATH}

        # add to the $PATH according to github docs
        echo "$HOME/.local/bin" >> $GITHUB_PATH

        # examine the path after
        echo "PATH AFTER:"
        echo ${PATH}

        # run fully qualified
        $HOME/.local/bin/works.sh

        # run via $PATH
        works.sh

    - shell: bash
      run: |
        # run via $PATH in subsequent step
        works.sh
